MOUSEKEY_ENABLE = yes
CONSUMER_CONTROL_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
SPI_ENABLE = yes


MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
DEBUG_ENABLE = yes
SPI_DRIVER = SPID0

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
SPI_DRIVER_REQUIRED = yes
